services:
  laravel.test:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: duplicationhub/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1001}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html:cached'
      - sailstorage:/var/www/html/storage
      - sailcache:/var/www/html/bootstrap/cache
    networks:
      - sail
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_EXPOSE_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-12345}'
      MYSQL_DATABASE: '${DB_DATABASE:-duplicationhub_api}'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - sailmysql:/var/lib/mysql
      - ./docker/my.cnf:/etc/my.cnf
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - '${DB_ADMIN_PORT:-8083}:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '${DB_PASSWORD:-12345}'
      UPLOAD_LIMIT: 30M
    depends_on:
      - mysql
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sailstorage:
    driver: local
  sailcache:
    driver: local
  sailmysql:
    driver: local
