services:
  laravel.test:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1000}'
    image: duplicationhub/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - .:/var/www/html:cached
    networks:
      - sail
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  mysql:
    image: mysql:8.0-oracle
    ports:
      - '${DB_PORT:-3305}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: duplicationhub_api
    volumes:
      - 'sailmysql:/var/lib/mysql'
      - './mysql-logs:/var/log/mysql'   # Mount logs folder to host
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p12345"]
      retries: 3
      timeout: 5s
    command:
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow.log

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8083:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345
    depends_on:
      - mysql
    networks:
      - sail


networks:
  sail:
    driver: bridge

volumes:
  sailmysql:
    driver: local
